dist: xenial
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - cppcheck
services:
  - docker
before_install:
    - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update -q
    - sudo apt-get install -y gcc-arm-embedded python3-venv
script:
  - export CC=gcc-8
  - pyenv shell 3.6.7
  - make travis
